# Generated by Django 4.2.24 on 2025-09-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('telegram', 'Telegram'), ('any', 'Any')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='tried_channels',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
